//
//  NetworkMock.swift
//  BeerBuddy
//
//  Created by Ke4a on 06.02.2023.
//
// swiftlint: disable function_body_length

import Foundation

protocol NetworkMockProtocol {
    func fetchChats() -> [ChatModelStub]
}

class NetworkMock: NetworkMockProtocol {
    func fetchChats() -> [ChatModelStub] {
        let now = Date()

        return [ .init(id: 0,
                       date: now.timeIntervalSince1970),
                 .init(id: 1,
                       date: Calendar.current.date(byAdding: .second,
                                                   value: -10, to: now)!.timeIntervalSince1970),
                 .init(id: 2,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 1...100), to: now)!.timeIntervalSince1970),
                 .init(id: 3,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 500...1000), to: now)!.timeIntervalSince1970),
                 .init(id: 4,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 12...16), to: now)!.timeIntervalSince1970),
                 .init(id: 5,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 16...24), to: now)!.timeIntervalSince1970),
                 .init(id: 6,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 2...6), to: now)!.timeIntervalSince1970),
                 .init(id: 7,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 6...12), to: now)!.timeIntervalSince1970),
                 .init(id: 8,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 12...24), to: now)!.timeIntervalSince1970),
                 .init(id: 9,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 60...500), to: now)!.timeIntervalSince1970),
                 .init(id: 10,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 500...1000), to: now)!.timeIntervalSince1970),
                 .init(id: 11,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 12...16), to: now)!.timeIntervalSince1970),
                 .init(id: 12,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 16...24), to: now)!.timeIntervalSince1970),
                 .init(id: 13,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 2...6), to: now)!.timeIntervalSince1970),
                 .init(id: 14,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 6...12), to: now)!.timeIntervalSince1970),
                 .init(id: 15,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 12...24), to: now)!.timeIntervalSince1970),
                 .init(id: 16,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 60...500), to: now)!.timeIntervalSince1970),
                 .init(id: 17,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 500...1000), to: now)!.timeIntervalSince1970),
                 .init(id: 18,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 12...16), to: now)!.timeIntervalSince1970),
                 .init(id: 19,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 16...24), to: now)!.timeIntervalSince1970),
                 .init(id: 20,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 2...6), to: now)!.timeIntervalSince1970),
                 .init(id: 21,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 6...12), to: now)!.timeIntervalSince1970),
                 .init(id: 22,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 12...24), to: now)!.timeIntervalSince1970),
                 .init(id: 23,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 60...500), to: now)!.timeIntervalSince1970),
                 .init(id: 24,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 500...1000), to: now)!.timeIntervalSince1970),
                 .init(id: 25,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 12...16), to: now)!.timeIntervalSince1970),
                 .init(id: 26,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 16...24), to: now)!.timeIntervalSince1970),
                 .init(id: 27,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 2...6), to: now)!.timeIntervalSince1970),
                 .init(id: 28,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 6...12), to: now)!.timeIntervalSince1970),
                 .init(id: 29,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 12...24), to: now)!.timeIntervalSince1970),
                 .init(id: 30,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 60...500), to: now)!.timeIntervalSince1970),
                 .init(id: 31,
                       date: Calendar.current.date(byAdding: .minute,
                                                   value: -Int.random(in: 500...1000), to: now)!.timeIntervalSince1970),
                 .init(id: 32,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 12...16), to: now)!.timeIntervalSince1970),
                 .init(id: 33,
                       date: Calendar.current.date(byAdding: .hour,
                                                   value: -Int.random(in: 16...24), to: now)!.timeIntervalSince1970),
                 .init(id: 34,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 2...6), to: now)!.timeIntervalSince1970),
                 .init(id: 35,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 6...12), to: now)!.timeIntervalSince1970),
                 .init(id: 36,
                       date: Calendar.current.date(byAdding: .day,
                                                   value: -Int.random(in: 12...24), to: now)!.timeIntervalSince1970)]
    }
}
